version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    volumes:
      - "./integration-tests:/integration-tests"
      - "./screenshots:/screenshots"
    command: "wait-for-it.sh tools.shuax.com/chrome:443 -- mocha --recursive /integration-tests"
