version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    volumes:
      - "./integration-tests:/integration-tests"
      - "./screenshots:/screenshots"
    command: "node /integration-tests/index.test.js"
