name: Puppeteer Build & Test

on: [push]

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://translate.google.com
        destination: screenshot-${{ matrix.os }}.png
    - name: 'Accidently upload to the same artifact via multiple jobs'
          uses: 'actions/upload-artifact@v2'
          with:
              name: my-artifact-${{ matrix.os }}
              path: screenshot-${{ matrix.os }}.png
